### ISSUE TITLE
Warm Afternoon Nap visual glitch

### ISSUE THREAD

**Issue by Sakimotor** [requinDr/tsukiweb-public#3] opened 2023-11-30 18:45 UTC
![firefox_fPk2Jhhwd7](https://github.com/requinDr/tsukiweb-public/assets/20578016/dce57091-d53f-41bb-b032-558a651cd642)

Ever since the last scene of Finale, the screen has that blue filter, doesn't seem to be t he original behaviour according to what I've seen in recorded footage of the original game. The save previews also seem glitched out

<details>
  <summary>Saves Preview</summary>

![firefox_mkCoci5xuh](https://github.com/requinDr/tsukiweb-public/assets/20578016/2d6c46ba-b2bb-4c37-9b1e-e393cbb86263)

</details>

**Comment by loicfrance** [comment] 2023-11-30 22:21
I can't reproduce this issue, Could you determine where exactly does the monochrome effect start ?
For debug purpose, you can move from scene to scene by calling `script.moveTo('sXXX')` in the developer console, and mess with the character affection using `progress.regard.akiha = 10` (replace `akiha` with the character you want and 10 with the desired value). the complete detailed flowchart can be read online here: https://pdfhost.io/v/SASZsaVY8_Tsukihime_Walkthrough_Flowchart.pdf. The "_knock knock_" on your screenshot appears in scene s385, end of akiha route

**Comment by loicfrance** [comment] 2023-11-30 22:22
The save previews should be fixed in the next update.

**Comment by loicfrance** [comment] 2023-12-01 09:13
Oh, ok, I get it. The command to disable the monochrome effect is at the beginning of scène s370, so if you skip this scene, the effect stays active. I will see if I can come up with a clean solution that does not involve modifying the scripts.
Thank you for your help.

**Closed** 2023-12-02 23:28 UTC

**Comment by loicfrance** [comment] 2023-12-02 23:35
I made sure the monochrome effect is disabled at the beginning of all scenes. This particular issue will be fixed in the next update.
However, similar issues will arise for scenes that rely on the previous scene to start a track, display sprites or background, etc.
We will eventually have to preprocess the script files anyway and manually add the missing sprites / tracks / others manually, as these issues are difficult to correct automatically.
